import { Type } from "@sinclair/typebox";

const ObjTypeSchema = Type.Union([
  Type.Literal("doc"),
  Type.Literal("sheet"),
  Type.Literal("mindnote"),
  Type.Literal("bitable"),
  Type.Literal("file"),
  Type.Literal("docx"),
  Type.Literal("slides"),
]);

export const FEISHU_USER_KB_SCHEMA = Type.Object(
  {
    action: Type.Union([
      Type.Literal("auth_status"),
      Type.Literal("start_auth"),
      Type.Literal("spaces"),
      Type.Literal("nodes"),
      Type.Literal("get_node"),
      Type.Literal("create_page"),
      Type.Literal("read_page"),
      Type.Literal("write_page"),
      Type.Literal("append_page"),
      Type.Literal("rename_node"),
      Type.Literal("move_node"),
      Type.Literal("move_doc_to_wiki"),
      Type.Literal("get_task"),
      Type.Literal("get_bitable"),
      Type.Literal("create_bitable"),
      Type.Literal("list_bitable_tables"),
      Type.Literal("create_bitable_table"),
      Type.Literal("list_bitable_fields"),
      Type.Literal("create_bitable_field"),
      Type.Literal("list_bitable_records"),
      Type.Literal("get_bitable_record"),
      Type.Literal("create_bitable_record"),
      Type.Literal("update_bitable_record"),
    ]),
    space_id: Type.Optional(Type.String()),
    parent_node_token: Type.Optional(Type.String()),
    node_token: Type.Optional(Type.String()),
    doc_token: Type.Optional(Type.String()),
    app_token: Type.Optional(Type.String()),
    obj_token: Type.Optional(Type.String()),
    obj_type: Type.Optional(ObjTypeSchema),
    title: Type.Optional(Type.String()),
    content: Type.Optional(Type.String()),
    target_space_id: Type.Optional(Type.String()),
    target_parent_token: Type.Optional(Type.String()),
    task_id: Type.Optional(Type.String()),
    wait_for_completion: Type.Optional(Type.Boolean()),
    table_id: Type.Optional(Type.String()),
    table_name: Type.Optional(Type.String()),
    default_view_name: Type.Optional(Type.String()),
    table_fields: Type.Optional(Type.Array(Type.Any())),
    field_name: Type.Optional(Type.String()),
    field_type: Type.Optional(Type.Number()),
    property: Type.Optional(Type.Record(Type.String(), Type.Any())),
    record_id: Type.Optional(Type.String()),
    fields: Type.Optional(Type.Record(Type.String(), Type.Any())),
    page_size: Type.Optional(Type.Number()),
    page_token: Type.Optional(Type.String()),
  },
  { additionalProperties: false },
);
